name: Update Satellite Data
on:
  schedule:
    - cron: '0 */12 * * *' # Corre a cada 12 horas
  workflow_dispatch: # Permite-te correr manualmente para testar

jobs:
  update-tle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Download TLE from CelesTrak
        run: |
          curl -o data.tle "https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=tle"
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.tle
          git commit -m "Update satellite data" || exit 0
          git push
